// Complete list of countries and territories with ISO 3166-1 alpha-2 and alpha-3 codes
export const COUNTRIES = [
  { code: 'AF', iso3: 'AFG', name: 'AFGHANISTAN' },
  { code: 'AL', iso3: 'ALB', name: 'ALBANIA' },
  { code: 'DZ', iso3: 'DZA', name: 'ALGERIA' },
  { code: 'AS', iso3: 'ASM', name: 'AMERICAN SAMOA' },
  { code: 'AD', iso3: 'AND', name: 'ANDORRA' },
  { code: 'AO', iso3: 'AGO', name: 'ANGOLA' },
  { code: 'AI', iso3: 'AIA', name: 'ANGUILLA' },
  { code: 'AQ', iso3: 'ATA', name: 'ANTARCTICA' },
  { code: 'AG', iso3: 'ATG', name: 'ANTIGUA AND BARBUDA' },
  { code: 'AR', iso3: 'ARG', name: 'ARGENTINA' },
  { code: 'AM', iso3: 'ARM', name: 'ARMENIA' },
  { code: 'AW', iso3: 'ABW', name: 'ARUBA' },
  { code: 'AU', iso3: 'AUS', name: 'AUSTRALIA' },
  { code: 'AT', iso3: 'AUT', name: 'AUSTRIA' },
  { code: 'AZ', iso3: 'AZE', name: 'AZERBAIJAN' },
  { code: 'BS', iso3: 'BHS', name: 'BAHAMAS' },
  { code: 'BH', iso3: 'BHR', name: 'BAHRAIN' },
  { code: 'BD', iso3: 'BGD', name: 'BANGLADESH' },
  { code: 'BB', iso3: 'BRB', name: 'BARBADOS' },
  { code: 'BY', iso3: 'BLR', name: 'BELARUS' },
  { code: 'BE', iso3: 'BEL', name: 'BELGIUM' },
  { code: 'BZ', iso3: 'BLZ', name: 'BELIZE' },
  { code: 'BJ', iso3: 'BEN', name: 'BENIN' },
  { code: 'BM', iso3: 'BMU', name: 'BERMUDA' },
  { code: 'BT', iso3: 'BTN', name: 'BHUTAN' },
  { code: 'BO', iso3: 'BOL', name: 'BOLIVIA' },
  { code: 'BA', iso3: 'BIH', name: 'BOSNIA AND HERZEGOVINA' },
  { code: 'BW', iso3: 'BWA', name: 'BOTSWANA' },
  { code: 'BR', iso3: 'BRA', name: 'BRAZIL' },
  { code: 'BN', iso3: 'BRN', name: 'BRUNEI' },
  { code: 'BG', iso3: 'BGR', name: 'BULGARIA' },
  { code: 'BF', iso3: 'BFA', name: 'BURKINA FASO' },
  { code: 'BI', iso3: 'BDI', name: 'BURUNDI' },
  { code: 'CV', iso3: 'CPV', name: 'CABO VERDE' },
  { code: 'KH', iso3: 'KHM', name: 'CAMBODIA' },
  { code: 'CM', iso3: 'CMR', name: 'CAMEROON' },
  { code: 'CA', iso3: 'CAN', name: 'CANADA' },
  { code: 'KY', iso3: 'CYM', name: 'CAYMAN ISLANDS' },
  { code: 'CF', iso3: 'CAF', name: 'CENTRAL AFRICAN REPUBLIC' },
  { code: 'TD', iso3: 'TCD', name: 'CHAD' },
  { code: 'CL', iso3: 'CHL', name: 'CHILE' },
  { code: 'CN', iso3: 'CHN', name: 'CHINA' },
  { code: 'CO', iso3: 'COL', name: 'COLOMBIA' },
  { code: 'KM', iso3: 'COM', name: 'COMOROS' },
  { code: 'CG', iso3: 'COG', name: 'CONGO' },
  { code: 'CD', iso3: 'COD', name: 'CONGO (DRC)' },
  { code: 'CR', iso3: 'CRI', name: 'COSTA RICA' },
  { code: 'CI', iso3: 'CIV', name: "CÔTE D'IVOIRE" },
  { code: 'HR', iso3: 'HRV', name: 'CROATIA' },
  { code: 'CU', iso3: 'CUB', name: 'CUBA' },
  { code: 'CY', iso3: 'CYP', name: 'CYPRUS' },
  { code: 'CZ', iso3: 'CZE', name: 'CZECH REPUBLIC' },
  { code: 'DK', iso3: 'DNK', name: 'DENMARK' },
  { code: 'DJ', iso3: 'DJI', name: 'DJIBOUTI' },
  { code: 'DM', iso3: 'DMA', name: 'DOMINICA' },
  { code: 'DO', iso3: 'DOM', name: 'DOMINICAN REPUBLIC' },
  { code: 'EC', iso3: 'ECU', name: 'ECUADOR' },
  { code: 'EG', iso3: 'EGY', name: 'EGYPT' },
  { code: 'SV', iso3: 'SLV', name: 'EL SALVADOR' },
  { code: 'GQ', iso3: 'GNQ', name: 'EQUATORIAL GUINEA' },
  { code: 'ER', iso3: 'ERI', name: 'ERITREA' },
  { code: 'EE', iso3: 'EST', name: 'ESTONIA' },
  { code: 'SZ', iso3: 'SWZ', name: 'ESWATINI' },
  { code: 'ET', iso3: 'ETH', name: 'ETHIOPIA' },
  { code: 'FJ', iso3: 'FJI', name: 'FIJI' },
  { code: 'FI', iso3: 'FIN', name: 'FINLAND' },
  { code: 'FR', iso3: 'FRA', name: 'FRANCE' },
  { code: 'GA', iso3: 'GAB', name: 'GABON' },
  { code: 'GM', iso3: 'GMB', name: 'GAMBIA' },
  { code: 'GE', iso3: 'GEO', name: 'GEORGIA' },
  { code: 'DE', iso3: 'DEU', name: 'GERMANY' },
  { code: 'GH', iso3: 'GHA', name: 'GHANA' },
  { code: 'GI', iso3: 'GIB', name: 'GIBRALTAR' },
  { code: 'GR', iso3: 'GRC', name: 'GREECE' },
  { code: 'GL', iso3: 'GRL', name: 'GREENLAND' },
  { code: 'GD', iso3: 'GRD', name: 'GRENADA' },
  { code: 'GU', iso3: 'GUM', name: 'GUAM' },
  { code: 'GT', iso3: 'GTM', name: 'GUATEMALA' },
  { code: 'GN', iso3: 'GIN', name: 'GUINEA' },
  { code: 'GW', iso3: 'GNB', name: 'GUINEA-BISSAU' },
  { code: 'GY', iso3: 'GUY', name: 'GUYANA' },
  { code: 'HT', iso3: 'HTI', name: 'HAITI' },
  { code: 'HN', iso3: 'HND', name: 'HONDURAS' },
  { code: 'HK', iso3: 'HKG', name: 'HONG KONG' },
  { code: 'HU', iso3: 'HUN', name: 'HUNGARY' },
  { code: 'IS', iso3: 'ISL', name: 'ICELAND' },
  { code: 'IN', iso3: 'IND', name: 'INDIA' },
  { code: 'ID', iso3: 'IDN', name: 'INDONESIA' },
  { code: 'IR', iso3: 'IRN', name: 'IRAN' },
  { code: 'IQ', iso3: 'IRQ', name: 'IRAQ' },
  { code: 'IE', iso3: 'IRL', name: 'IRELAND' },
  { code: 'IL', iso3: 'ISR', name: 'ISRAEL' },
  { code: 'IT', iso3: 'ITA', name: 'ITALY' },
  { code: 'JM', iso3: 'JAM', name: 'JAMAICA' },
  { code: 'JP', iso3: 'JPN', name: 'JAPAN' },
  { code: 'JO', iso3: 'JOR', name: 'JORDAN' },
  { code: 'KZ', iso3: 'KAZ', name: 'KAZAKHSTAN' },
  { code: 'KE', iso3: 'KEN', name: 'KENYA' },
  { code: 'KI', iso3: 'KIR', name: 'KIRIBATI' },
  { code: 'KP', iso3: 'PRK', name: 'KOREA (NORTH)' },
  { code: 'KR', iso3: 'KOR', name: 'KOREA (SOUTH)' },
  { code: 'KW', iso3: 'KWT', name: 'KUWAIT' },
  { code: 'KG', iso3: 'KGZ', name: 'KYRGYZSTAN' },
  { code: 'LA', iso3: 'LAO', name: 'LAOS' },
  { code: 'LV', iso3: 'LVA', name: 'LATVIA' },
  { code: 'LB', iso3: 'LBN', name: 'LEBANON' },
  { code: 'LS', iso3: 'LSO', name: 'LESOTHO' },
  { code: 'LR', iso3: 'LBR', name: 'LIBERIA' },
  { code: 'LY', iso3: 'LBY', name: 'LIBYA' },
  { code: 'LI', iso3: 'LIE', name: 'LIECHTENSTEIN' },
  { code: 'LT', iso3: 'LTU', name: 'LITHUANIA' },
  { code: 'LU', iso3: 'LUX', name: 'LUXEMBOURG' },
  { code: 'MO', iso3: 'MAC', name: 'MACAO' },
  { code: 'MG', iso3: 'MDG', name: 'MADAGASCAR' },
  { code: 'MW', iso3: 'MWI', name: 'MALAWI' },
  { code: 'MY', iso3: 'MYS', name: 'MALAYSIA' },
  { code: 'MV', iso3: 'MDV', name: 'MALDIVES' },
  { code: 'ML', iso3: 'MLI', name: 'MALI' },
  { code: 'MT', iso3: 'MLT', name: 'MALTA' },
  { code: 'MH', iso3: 'MHL', name: 'MARSHALL ISLANDS' },
  { code: 'MR', iso3: 'MRT', name: 'MAURITANIA' },
  { code: 'MU', iso3: 'MUS', name: 'MAURITIUS' },
  { code: 'MX', iso3: 'MEX', name: 'MEXICO' },
  { code: 'FM', iso3: 'FSM', name: 'MICRONESIA' },
  { code: 'MD', iso3: 'MDA', name: 'MOLDOVA' },
  { code: 'MC', iso3: 'MCO', name: 'MONACO' },
  { code: 'MN', iso3: 'MNG', name: 'MONGOLIA' },
  { code: 'ME', iso3: 'MNE', name: 'MONTENEGRO' },
  { code: 'MA', iso3: 'MAR', name: 'MOROCCO' },
  { code: 'MZ', iso3: 'MOZ', name: 'MOZAMBIQUE' },
  { code: 'MM', iso3: 'MMR', name: 'MYANMAR' },
  { code: 'NA', iso3: 'NAM', name: 'NAMIBIA' },
  { code: 'NR', iso3: 'NRU', name: 'NAURU' },
  { code: 'NP', iso3: 'NPL', name: 'NEPAL' },
  { code: 'NL', iso3: 'NLD', name: 'NETHERLANDS' },
  { code: 'NZ', iso3: 'NZL', name: 'NEW ZEALAND' },
  { code: 'NI', iso3: 'NIC', name: 'NICARAGUA' },
  { code: 'NE', iso3: 'NER', name: 'NIGER' },
  { code: 'NG', iso3: 'NGA', name: 'NIGERIA' },
  { code: 'MK', iso3: 'MKD', name: 'NORTH MACEDONIA' },
  { code: 'NO', iso3: 'NOR', name: 'NORWAY' },
  { code: 'OM', iso3: 'OMN', name: 'OMAN' },
  { code: 'PK', iso3: 'PAK', name: 'PAKISTAN' },
  { code: 'PW', iso3: 'PLW', name: 'PALAU' },
  { code: 'PS', iso3: 'PSE', name: 'PALESTINE' },
  { code: 'PA', iso3: 'PAN', name: 'PANAMA' },
  { code: 'PG', iso3: 'PNG', name: 'PAPUA NEW GUINEA' },
  { code: 'PY', iso3: 'PRY', name: 'PARAGUAY' },
  { code: 'PE', iso3: 'PER', name: 'PERU' },
  { code: 'PH', iso3: 'PHL', name: 'PHILIPPINES' },
  { code: 'PL', iso3: 'POL', name: 'POLAND' },
  { code: 'PT', iso3: 'PRT', name: 'PORTUGAL' },
  { code: 'PR', iso3: 'PRI', name: 'PUERTO RICO' },
  { code: 'QA', iso3: 'QAT', name: 'QATAR' },
  { code: 'RO', iso3: 'ROU', name: 'ROMANIA' },
  { code: 'RU', iso3: 'RUS', name: 'RUSSIA' },
  { code: 'RW', iso3: 'RWA', name: 'RWANDA' },
  { code: 'KN', iso3: 'KNA', name: 'SAINT KITTS AND NEVIS' },
  { code: 'LC', iso3: 'LCA', name: 'SAINT LUCIA' },
  { code: 'VC', iso3: 'VCT', name: 'SAINT VINCENT AND THE GRENADINES' },
  { code: 'WS', iso3: 'WSM', name: 'SAMOA' },
  { code: 'SM', iso3: 'SMR', name: 'SAN MARINO' },
  { code: 'ST', iso3: 'STP', name: 'SAO TOME AND PRINCIPE' },
  { code: 'SA', iso3: 'SAU', name: 'SAUDI ARABIA' },
  { code: 'SN', iso3: 'SEN', name: 'SENEGAL' },
  { code: 'RS', iso3: 'SRB', name: 'SERBIA' },
  { code: 'SC', iso3: 'SYC', name: 'SEYCHELLES' },
  { code: 'SL', iso3: 'SLE', name: 'SIERRA LEONE' },
  { code: 'SG', iso3: 'SGP', name: 'SINGAPORE' },
  { code: 'SK', iso3: 'SVK', name: 'SLOVAKIA' },
  { code: 'SI', iso3: 'SVN', name: 'SLOVENIA' },
  { code: 'SB', iso3: 'SLB', name: 'SOLOMON ISLANDS' },
  { code: 'SO', iso3: 'SOM', name: 'SOMALIA' },
  { code: 'ZA', iso3: 'ZAF', name: 'SOUTH AFRICA' },
  { code: 'SS', iso3: 'SSD', name: 'SOUTH SUDAN' },
  { code: 'ES', iso3: 'ESP', name: 'SPAIN' },
  { code: 'LK', iso3: 'LKA', name: 'SRI LANKA' },
  { code: 'SD', iso3: 'SDN', name: 'SUDAN' },
  { code: 'SR', iso3: 'SUR', name: 'SURINAME' },
  { code: 'SE', iso3: 'SWE', name: 'SWEDEN' },
  { code: 'CH', iso3: 'CHE', name: 'SWITZERLAND' },
  { code: 'SY', iso3: 'SYR', name: 'SYRIA' },
  { code: 'TW', iso3: 'TWN', name: 'TAIWAN' },
  { code: 'TJ', iso3: 'TJK', name: 'TAJIKISTAN' },
  { code: 'TZ', iso3: 'TZA', name: 'TANZANIA' },
  { code: 'TH', iso3: 'THA', name: 'THAILAND' },
  { code: 'TL', iso3: 'TLS', name: 'TIMOR-LESTE' },
  { code: 'TG', iso3: 'TGO', name: 'TOGO' },
  { code: 'TO', iso3: 'TON', name: 'TONGA' },
  { code: 'TT', iso3: 'TTO', name: 'TRINIDAD AND TOBAGO' },
  { code: 'TN', iso3: 'TUN', name: 'TUNISIA' },
  { code: 'TR', iso3: 'TUR', name: 'TURKEY' },
  { code: 'TM', iso3: 'TKM', name: 'TURKMENISTAN' },
  { code: 'TV', iso3: 'TUV', name: 'TUVALU' },
  { code: 'UG', iso3: 'UGA', name: 'UGANDA' },
  { code: 'UA', iso3: 'UKR', name: 'UKRAINE' },
  { code: 'AE', iso3: 'ARE', name: 'UNITED ARAB EMIRATES' },
  { code: 'GB', iso3: 'GBR', name: 'UNITED KINGDOM' },
  { code: 'US', iso3: 'USA', name: 'UNITED STATES' },
  { code: 'UY', iso3: 'URY', name: 'URUGUAY' },
  { code: 'UZ', iso3: 'UZB', name: 'UZBEKISTAN' },
  { code: 'VU', iso3: 'VUT', name: 'VANUATU' },
  { code: 'VA', iso3: 'VAT', name: 'VATICAN CITY' },
  { code: 'VE', iso3: 'VEN', name: 'VENEZUELA' },
  { code: 'VN', iso3: 'VNM', name: 'VIETNAM' },
  { code: 'VG', iso3: 'VGB', name: 'VIRGIN ISLANDS, BRITISH' },
  { code: 'VI', iso3: 'VIR', name: 'VIRGIN ISLANDS, U.S.' },
  { code: 'YE', iso3: 'YEM', name: 'YEMEN' },
  { code: 'ZM', iso3: 'ZMB', name: 'ZAMBIA' },
  { code: 'ZW', iso3: 'ZWE', name: 'ZIMBABWE' }
];

export const getCountryName = (codeOrName) => {
  if (!codeOrName) return '';
  const match = COUNTRIES.find(
    c => c.code.toUpperCase() === codeOrName.toUpperCase() ||
         c.iso3.toUpperCase() === codeOrName.toUpperCase() ||
         c.name.toUpperCase() === codeOrName.toUpperCase()
  );
  return match ? match.name : codeOrName;
};

export const getCountryCode = (codeOrName) => {
  if (!codeOrName) return '';
  const match = COUNTRIES.find(
    c => c.code.toUpperCase() === codeOrName.toUpperCase() ||
         c.iso3.toUpperCase() === codeOrName.toUpperCase() ||
         c.name.toUpperCase() === codeOrName.toUpperCase()
  );
  return match ? match.code : codeOrName;
};
